import Document, { Html, Head, Main, NextScript } from 'next/document'
import $ from 'jquery';

class MyDocument extends Document {
  static async getInitialProps(ctx) {
    const initialProps = await Document.getInitialProps(ctx)
    return { ...initialProps }
  }

  render() {
    return (
      <Html lang='en'>
        <Head>
          <meta name='description' content='Generated by create next app' />
          <link
            rel='shortcut icon'
            type='image/x-icon'
            href='bootstrap4/images/logo1.png'
          />
          <link
            // href='https://tezeract-ai.github.io/yatra-travel-template/css/bootstrap.min.css'
            href='bootstrap4/css/bootstrap.min.css'
            rel='stylesheet'
            type='text/css'
          />
          <link
            // href='https://tezeract-ai.github.io/yatra-travel-template/css/style.css'
            href='bootstrap4/css/style.css'
            rel='stylesheet'
            type='text/css'
          />
          <link
            // href='https://tezeract-ai.github.io/yatra-travel-template/font/flaticon.css'
            href='bootstrap4/font/flaticon.css'
            rel='stylesheet'
            type='text/css'
          />
          <link
            href='bootstrap4/css/icons.css'
            rel='stylesheet'
            type='text/css'
          />
          <link
            // href='https://tezeract-ai.github.io/yatra-travel-template/css/plugin.css'
            href='bootstrap4/css/plugin.css'
            rel='stylesheet'
            type='text/css'
          />
          <link
            href='bootstrap4/css/dashboard.css'
            rel='stylesheet'
            type='text/css'
          />
          <link
            rel='stylesheet'
            href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css'
          />
        </Head>
        <body>
          <Main />
          <NextScript />
          {/* <script src='js/yawar-script.js'></script> */}
          <script src='js/jquery-3.2.1.min.js'></script>
          <script src='js/bootstrap.min.js'></script>
          <script src='js/plugin.js'></script>
          <script src='js/main.js'></script>
          <script src='js/main-1.js'></script>
          <script src='js/preloader.js'></script>
          <script src='js/custom-swiper2.js'></script>
          <script src='js/rangeslider.js'></script>
          <script src='js/custom-accordian.js'></script>
          <script src='https://code.jquery.com/jquery-migrate-1.4.1.min.js'></script>
          <script
            src='https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js'
            integrity='sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx'
            crossOrigin='anonymous'
          ></script>
          <script src='js/dashboard-custom.js'></script>
          <script src='https://canvasjs.com/assets/script/canvasjs.min.js'></script>
          <script src='js/chart.js'></script>
          <script src='js/jpanelmenu.min.js'></script>
          <script src='js/counterup.min.js'></script>


        </body>
      </Html>
    )
  }
}

export default MyDocument
